// chats
const chats = [
    {
        id: 1,
        name: "Pascaline",
        text: "how was your night",
        date: "2:00pm",
        img: "./img/avatar-7.jpg",
      },
    {
        id: 2,
        name: "Favour",
        text: "You Want Netflix and Chill?",
        date: "9:40pm",
        img: "./img/bg6.jpg",
       
      },
    {
        id: 3,
        name: "Isotope",
        text: "Send Me money",
        date: "4:50pm",
        img: "./img/image-001.jpg",
      },
    {
        id: 4,
        name: "Joyce",
        text: "how was your night",
        date: "10:00am",
        img: "./img/bg7.jpg",
      },
    {
        id: 5,
        name: "Victor",
        text: "how you doing",
        date: "2:00pm",
        img: "./img/call.jpg",
      },
    {
        id: 6,
        name: "Big Bro",
        text: "Send Me cash",
        date: "9:40pm",
        img: "./img/bg5.jpg",
      },
    {
        id: 7,
        name: "Bestie",
        text: "Send Me money",
        date: "4:50pm",
        img: "./img/bg6.jpg",
      },
    {
        id: 8,
        name: "Oluwatobiloba",
        text: "how was your night",
        date: "10:00am",
        img: "./img/bg7.jpg",
      },
    {
        id: 9,
        name: "Pancakes",
        text: "how was your night",
        date: "2:00pm",
        img: "./img/call.jpg",
      },
    {
        id: 10,
        name: "Olori Spendy",
        text: "You Want Netflix and Chill?",
        date: "9:40pm",
        img: "./img/bg5.jpg",
      },
    {
        id: 11,
        name: "Khush",
        text: "Send Me money",
        date: "4:50pm",
        img: "./img/bg6.jpg",
      },
    {
        id: 12,
        name: "Pancakes",
        text: "how was your night",
        date: "10:00am",
        img: "./img/bg7.jpg",
      },
    {
        id: 13,
        name: "Pancakes",
        text: "how was your night",
        date: "2:00pm",
        img: "./img/call.jpg",
      },
  ]
  
  // Recent
  const recent = [
    {
      id: 1,
      name: "Favry Pop",
      time: "20 minutes ago",
      img: "img/avatar-7.jpg",
      class: "frend"
    },
    {
      id: 2,
      name: "Isotope",
      time: "20 minutes ago",
      img: "img/person_2.jpg",
      class: "vendor",
    },
  {
      id: 3,
      name: "Stephen",
      time: "30 minutes ago",
      img: "./img/bg6.jpg",
      class: "frend",
    },
  {
      id: 4,
      name: "Oluwatobiloba",
      time: "35 minutes ago",
      img: "./img/bg7.jpg",
      class: "vendor"
    },
  {
      id: 5,
      name: "Pascaline",
      time: "40 minutes ago",
      img: "./img/call.jpg",
      class: "frend",
    },
  {
      id: 2,
      name: "Banky",
      time: "54 minutes ago",
      img: "img/bg5.jpg",
      class: "vendor",
    },
  ];
  
  // Viewed
  const viewed = [
    {
      id: 1,
      name: "Adore",
      time: "20 minutes ago",
      img: "./img/avatar-7.jpg",
      class: "frend",
    },
  {
      id: 2,
      name: "Philip Keys",
      time: "20 minutes ago",
      img: "./img/bg5.jpg",
      class: "plane",
    },
  {
      id: 3,
      name: "Anoi",
      time: "30 minutes ago",
      img: "./img/bg6.jpg",
      class: "frend",
    },
  {
      id: 4,
      name: "ABU",
      time: "35 minutes ago",
      img: "./img/bg7.jpg",
      class: "vendor",
    },
  {
      id: 5,
      name: "Micheal Rex",
      time: "40 minutes ago",
      img: "./img/call.jpg",
      class: "vendor",
    },
  {
      id: 2,
      name: "Joyce",
      time: "54 minutes ago",
      img: "./img/bg5.jpg",
      class: "frend",
    },
  ];
  
  //Calls
  const Calls = [
    {
        id: 1,
        time: " Today, 5.13PM",
        name: "Favry Pop",
        img: "./img/avatar-7.jpg",
        class: "outgoing",
        type: "fa fa-arrow-up",
      },
    {
        id: 2,
        time: " (100) Yesterday, 5.13PM",
        name: "Favry Pop",
        img: "./img/bg5.jpg",
        class: "incoming",
        type: "fa fa-arrow-down",
      },
    {
        id: 3,
        name: "Isotope",
        time: "Saturday 5:00pm",
        img: "./img/bg6.jpg",
        class: "incoming",
        type: "fa fa-arrow-down",
      },
    {
        id: 4,
        name: "Joyce",
        text: "how was your night",
        time: "Saturday 3:00pm",
        img: "./img/bg7.jpg",
        class: "outgoing",
        type: "fa fa-arrow-up",
      },
    {
        id: 5,
        name: "Victor",
        text: "how you doing",
        time: "Saturday 12:30pm",
        img: "./img/call.jpg",
        class: "incoming",
        type: "fa fa-arrow-down",
      },
    {
        id: 2,
        name: "Bestie",
        text: "Send Me cash",
        time: "Friday 11:50pm",
        img: "./img/bg6.jpg",
        class: "outgoing",
        type: "fa fa-arrow-up",
      },
    {
        id: 3,
        name: "Bestie",
        time: "(2) Friday 11:45pm",
        img: "./img/bg6.jpg",
        class: "incoming",
        type: "fa fa-arrow-down",
      },
    {
        id: 4,
        name: "Oluwatobiloba",
        time: "Thursday 7:30pm",
        img: "./img/bg7.jpg",
        class: "outgoing",
        type: "fa fa-arrow-up",
      },
    {
        id: 5,
        name: "Pancakes",
        text: "how was your night",
        time: "Wednesday 11:00pm",
        img: "./img/call.jpg",
        class: "outgoing",
        type: "fa fa-arrow-up",
      },
    {
        id: 2,
        name: "Olori Spendy",
        time: "(5) Wednesday 9:00am",
        img: "./img/bg5.jpg",
        class: "incoming",
        type: "fa fa-arrow-down",
      },
    {
        id: 3,
        name: "Khush",
        text: "Send Me money",
        time: "Tuesday 10:30pm",
        img: "./img/bg6.jpg",
        class: "outgoing",
        type: "fa fa-arrow-up",
      },
    {
        id: 4,
        name: "Pancakes",
        text: "how was your night",
        time: "(4) Tuesday 3:50pm",
        img: "./img/bg7.jpg",
        class: "incoming",
        type: "fa fa-arrow-down",
      },
    {
        id: 5,
        name: "Pancakes",
        text: "how was your night",
        time: "Monday 2:30pm",
        img: "./img/call.jpg",
        class: "incoming",
        type: "fa fa-arrow-down",
      },
  ] 